openapi: 3.0.1
info:
  title: BillAgreementStandardPayment
  description: Servicio diseñado para la notificación o pago de conceptos asociados
    a un convenio. El método  POST /Rollback permite reversar o debitar la notificación
    de un recaudo desde el canal de oficinas (Sofia).
  version: 1.0.0
servers:
- url: https://agreementsManagement/v1/Payments/Bill
paths:
  /Rollback:
    post:
      tags:
      - /Rollback
      summary: Reversar notificación del recaudo asociado a un convenio.
      description: Reversar la notificación o pago de los conceptos asociados a un
        convenio desde el canal de oficinas a nivel nacional (Sofia)
      operationId: RollbackbillAgreementPayment
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              $ref: '#/components/schemas/ReqbillAgreement'
        required: true
      responses:
        "201":
          description: Transacción Exitosa
          headers:
            X-ApprovalId:
              description: Número de autorización de la transacción
              schema:
                type: string
            X-RqUID:
              description: Identificador Unico de la transacción
              schema:
                type: string
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/RespbillAgreement'
        "206":
          description: Se genero un error de negocio
          headers:
            X-ApprovalId:
              description: Número de autorización de la transacción
              schema:
                type: string
            X-RqUID:
              description: Identificador Unico de la transacción
              schema:
                type: string
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/ErrorbillAgreement'
        "400":
          description: Petición incorrecta
          headers:
            X-ApprovalId:
              description: Número de autorización de la transacción
              schema:
                type: string
            X-RqUID:
              description: Identificador Unico de la transacción
              schema:
                type: string
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/ErrorbillAgreement'
        "408":
          description: Timeout del backend
          headers:
            X-ApprovalId:
              description: Número de autorización de la transacción
              schema:
                type: string
            X-RqUID:
              description: Identificador Unico de la transacción
              schema:
                type: string
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/ErrorbillAgreement'
        "412":
          description: RqUI requerido
          headers:
            X-ApprovalId:
              description: Número de autorización de la transacción
              schema:
                type: string
            X-RqUID:
              description: Identificador Unico de la transacción
              schema:
                type: string
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/ErrorbillAgreement'
        "420":
          description: Error en el backend
          headers:
            X-ApprovalId:
              description: Número de autorización de la transacción
              schema:
                type: string
            X-RqUID:
              description: Identificador Unico de la transacción
              schema:
                type: string
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/ErrorbillAgreement'
        "500":
          description: Error interno en el servidor
          headers:
            X-ApprovalId:
              description: Número de autorización de la transacción
              schema:
                type: string
            X-RqUID:
              description: Identificador Unico de la transacción
              schema:
                type: string
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/ErrorbillAgreement'
        "508":
          description: Timeout
          headers:
            X-ApprovalId:
              description: Número de autorización de la transacción
              schema:
                type: string
            X-RqUID:
              description: Identificador Unico de la transacción
              schema:
                type: string
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/ErrorbillAgreement'
      x-codegen-request-body-name: body
components:
  schemas:
    ReqbillAgreement:
      required:
      - race
      - InvoiceInfo
      type: object
      properties:
        trace:
          type: object
          required:
          - X-RqUID    
          - X-Channel
          - X-CompanyId
          - X-GovIssueIdentType
          - X-IdentSerialNum
          - X-BankId
          properties:
            X-RqUID:
              maxLength: 30
              minLength: 1
              type: string
              description: Identificador único de la transacción.
              example: "16012019000"
            X-Channel:
              maxLength: 20
              minLength: 1
              type: string
              description: Canal origen de la invocación.
              example: "CANALES"
            X-CompanyId:
              maxLength: 10
              minLength: 1
              type: string
              description: Código de la empresa que origina la invocación.
              example: "0002"
            X-GovIssueIdentType:
              type: string
              description: Tipo de identificación del operador que consume el servicio.
              example: "CC"
            X-IdentSerialNum:
              maxLength: 20
              minLength: 1
              type: string
              description: Número de identificación del operador que consume el servicio.
              example: "79845117"
            X-Version:
              type: string
              description: Versión de la aplicación.
              example: "1.0.0"
            X-BankIdType:
              maxLength: 15
              minLength: 0
              type: string
              description: Identificador del banco.
              example: "002"
            X-BankId:
              maxLength: 10
              minLength: 1
              type: string
              description: Código identificador del banco.
              example: "002"
            X-BranchId:
              maxLength: 20
              minLength: 0
              type: string
              description: Identificador de la Oficina /sucursal.
              example: "040"
            X-BranchName:
              type: string
              description: Nombre de la terminal.
              example: "W010956GZQ27"
            X-IPAddr:
              type: string
              description: IP origen de la invocación.
              example: "192.10.20.123"
            X-KeyAcctId:
              type: string
              description: Identificador interno.
              example: "2"
            X-NextDay:
              type: string
              format: date-time
              description: Fecha de compensación en formato DateTime. YYYY-MM-DDThh:mm:ss
              example: "2025-07-25"    
            X-Reverse:
              type: boolean
              default: True
              description: "Indicador de Reverso, con un valor booleano constante True"
        Period:
          type: string
          description: Fecha de la Transacción en formato DateTime
          format: date-time
        InvoiceInfo:
          $ref: '#/components/schemas/InvoiceInfo'
      description: Reversar notificación de los conceptos asociados a un convenio
    ErrorStatus:
      required:
      - Status
      type: object
      properties:
        Status:
          required:
          - AdditionalStatus
          - EndDt
          - Severity
          - StatusCode
          - StatusDesc
          type: object
          properties:
            StatusCode:
              type: string
              description: Código de respuesta del API
              enum:
              - "0"
              - "100"
            Severity:
              type: string
              description: Código de severidad de la respuesta
              example: Error
              enum:
              - Info
              - Error
            StatusDesc:
              maxLength: 300
              minLength: 1
              type: string
              description: Descripción del estado de la consulta
            AdditionalStatus:
              required:
              - ServerStatusCode
              - StatusDesc
              type: object
              properties:
                ServerStatusCode:
                  type: string
                  description: Código de respuesta del servidor
                Severity:
                  type: string
                  description: Código de severidad de la respuesta
                  example: Error
                StatusDesc:
                  maxLength: 300
                  minLength: 1
                  type: string
                  description: Descripción detallada del estado de la consulta
              description: Información adicional de la respuesta
            EndDt:
              type: string
              description: Fecha y hora de finalización en formato DataTime
              format: date-time
    InvoiceInfo:
      required:
      - Amt
      - CodeIAC
      - InvoiceNum
      - RqUID
      type: object
      properties:
        CodeIAC:
          type: string
          description: Código IAC del convenio
          example: "234658"
        InvoiceNum:
          maxLength: 35
          minLength: 1
          type: string
          description: "Número de factura, obligatorio para el negocio"
          example: "234658"
        Amt:
          type: number
          description: "Valor total por pagar"
          format: float
          maxLength: 20
          minLength: 1
          example: 5000.0
        RqUID:
          maxLength: 30
          minLength: 1
          type: string
          description: Identificador Único de la notificación o pago a reversar
          example: "16012019001"
        ExpDt:
          type: string
          description: "Fecha de expiración de la factura, en formato Date"
          format: date
          example: 2024-09-24
    MsgRsHdr:
      required:
      - Status
      type: object
      properties:
        Status:
          required:
          - AdditionalStatus
          - EndDt
          - Severity
          - StatusCode
          - StatusDesc
          type: object
          properties:
            StatusCode:
              type: string
              description: Codigo de respuesta del API
              example: "0"
              enum:
              - "0"
              - "100"
            Severity:
              type: string
              description: Codigo de severidad de la respuesta
              example: Info
              enum:
              - Info
              - Error
            StatusDesc:
              maxLength: 300
              minLength: 1
              type: string
              description: Descripción del estado de la notificación
              example: Transacción Exitosa
            AdditionalStatus:
              required:
              - ServerStatusCode
              - StatusDesc
              type: object
              properties:
                ServerStatusCode:
                  type: string
                  description: Código de respuesta del servidor
                  example: "0"
                Severity:
                  type: string
                  description: Codigo de severidad de la respuesta
                  example: Info
                  enum:
                  - Info
                  - Error
                StatusDesc:
                  maxLength: 300
                  minLength: 1
                  type: string
                  description: Descripción detallada del estado de la notificación
                  example: Se ha reversado el recaudo
              description: Información adicional de la respuesta
            EndDt:
              type: string
              description: Fecha y hora de finalización en formato DataTime
              format: date-time
    RespbillAgreement:
      required:
      - MsgRsHdr
      type: object
      properties:
        MsgRsHdr:
          $ref: '#/components/schemas/MsgRsHdr'
    ErrorbillAgreement:
      required:
      - MsgRsHdr
      type: object
      properties:
        MsgRsHdr:
          $ref: '#/components/schemas/ErrorStatus'